### ISSUE TITLE
Adapta theme content of eclipse debug window not visible.

### ISSUE THREAD

**Issue by prasadpatil25** [adapta-project/adapta-gtk-theme#420]
**Reporter info**
Hello,

I am Prasad Patil using adapta theme on Fedora 24. I am facing issue of missing content of window while using Eclipse mars version.

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - gtk2-2.24.31-1.fc24.x86_64
 * Desktop environment - Gnome Version 3.20.2
 ```

**Adapta version (if you knew)**
Latest version build from sources

**Related Application and/or Shell theming (or name of widget)**
Mars Eclipse (IDE for java development)

**Actual issue**
In case of Adapta theme content of debug window missing because of adapta shell theme whereas in case of Paper theme content of debug window is visible.

**Steps to reproduce (if you knew)**
Whenever used adapta  theme I face this problem where as in case of paper theme I have never felt this problem.

**Expected behaviour**
Content should be visible as show in paper theme.

**Other Note (feature-request, question, etc...)**
Please check out attachment for both paper and adapta theme. Screen shot shows the 2 different theme paper and adapta and missing content in case of adapta theme.

Paper theme:
![paper theme](https://cloud.githubusercontent.com/assets/12842912/26721331/1cd88894-47a9-11e7-95a8-aac99d344259.png)

Adapta theme:
![adapta theme](https://cloud.githubusercontent.com/assets/12842912/26721337/232462a4-47a9-11e7-83de-14aa157b9933.png)

**Comment by tista500** [comment]
I hardly use Eclipse, but I could not reproduce with a sample Java project:

![screenshot from 2017-06-03 06-33-32](https://cloud.githubusercontent.com/assets/6073622/26745807/597aab6e-4827-11e7-9d8f-4fe687ee24a8.png)

Eclipse: Mars.2 Release (4.5.2) from Official download
Openjdk-8:  1.8.0_131
Gtk+ 3.22.15

Regards.

**Comment by tista500** [comment]
Ah, this issue seems Gtk+ 2.x backend specific.

Fix was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/89688e945a29576b33a6f268837ebd92ef8f6421

Regards.

**Comment by prasadpatil25** [comment]
Yes, your are right. This issue is for Gtk+ 2.x version only. I am running eclipse on Gtk+ 2.x version. However issue is still there. I have downloaded latest sources and build on my system. I can see changes in files gtk/gtk-2.0/3rd-party-x.rc that you committed. Problem is not coming for dark skin but coming for only Adapta and Adapta-Eta.

**Comment by prasadpatil25** [comment]
I have created new file  `.gtkrc-eclipse` to solve this issue: 	
 
        # Create a new file in your home directory called .gtkrc-eclipse
 
	# call eclipse with this command:
	# Gtk2 forced:
	# export SWT_GTK3=0
	# env GTK2_RC_FILES=/usr/share/themes/<YourTheme>/gtk-2.0/gtkrc:/home/<YourUser>/.gtkrc-eclipse '/path_to_eclipse/eclipse'

	# In your Eclipse directory find the file 'e4_default_gtk.css'
	# In this file there's a CSS class:

	# .MPartStack {
	#     font-size: 11;
	#     swt-simple: false;
	#     swt-mru-visible: false;
	# }
	# .gtkrc-eclipse

	#To set the Gtk theme
	#include "/usr/share/themes/Paper/gtk-2.0/gtkrc"
	#gtk-icon-theme-name = "paper"

	style "gtkcompact" {
		GtkButton::default_border={0,0,0,0}
		GtkButton::default_outside_border={0,0,0,0}
		GtkButtonBox::child_min_width=0
		GtkButtonBox::child_min_heigth=0
		GtkButtonBox::child_internal_pad_x=0
		GtkButtonBox::child_internal_pad_y=0
		GtkMenu::vertical-padding=1
		GtkMenuBar::internal_padding=0
		GtkMenuItem::horizontal_padding=4
		GtkToolbar::internal-padding=0
		GtkToolbar::space-size=0
		GtkOptionMenu::indicator_size=0
		GtkOptionMenu::indicator_spacing=0
		GtkPaned::handle_size=1
		GtkRange::trough_border=0
		GtkRange::stepper_spacing=0
		GtkScale::value_spacing=0
		GtkScrolledWindow::scrollbar_spacing=0
		GtkTreeView::vertical-separator=0
		GtkTreeView::horizontal-separator=0
		GtkTreeView::fixed-height-mode=TRUE
		GtkWidget::focus_padding=0
	       GtkWidget::tooltip-radius    = 3
	       GtkWidget::tooltip-alpha     = 235
	       GtkWidget::new-tooltip-style = 1 #for compatibility
	}
	class "GtkWidget" style "gtkcompact"

	# Make tabs smaller
	style "compact-toolbar" {
		GtkToolbar::internal-padding = 0
		xthickness = 1
		ythickness = 1
	}

	style "compact-button" {
		xthickness = 0
		ythickness = 0
	}

	style "eclipse-tooltips" {
	  xthickness = 4
	  ythickness = 4
	}

	widget "gtk-tooltips*"     style "eclipse-tooltips"

	style "compact-default"
	{
	  xthickness=1
	  ythickness=1
	}

	style "compact-entry"
	{
	  xthickness=2
	  ythickness=2
	}
	class "GtkButton" style "compact-default"
	class "GtkPaned" style "compact-default"
	class "GtkEntry" style "compact-entry" 
	class "GtkMenuItem" style "compact-button"
	# Added latter ends

	class "GtkToolbar" style "compact-toolbar"
	widget_class "*<GtkToolbar>*<GtkButton>" style "compact-button"

The below line solved my issue related with eclipse tooltips:

        style "eclipse-tooltips" {
	  xthickness = 4
	  ythickness = 4
	}

And then I called this file using following commands:

        export SWT_GTK3=0
        env GTK2_RC_FILES=/usr/share/themes/Adapta-Eta/gtk-2.0/gtkrc:/home/patil/.gtkrc-eclipse /home/prasad/Mars3/eclipse

**Comment by prasadpatil25** [comment]
Hello Tista,

This problem has been solved by your commit. I was using custom .gtkrc file which was preventing your changes to get reflect in Eclipse's tooltips. Please make sure you these 2 below lines:

     +  bg[NORMAL] = @secondary_dark_color
     +  fg[NORMAL] = @fg_color
